name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        cmake .. -DROCKSDB_GIT_REPO=https://github.com/facebook/rocksdb.git -DROCKSDB_GIT_BRANCH=5.18.fb
        make
        ctest -R titan
